apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-mgmt-service
  namespace: user-mgmt
  spec:
    ingressClassName: traefik
spec:
  rules:
    - host: user-mgmt.example.com
      http:
        paths:
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: user-mgmt-service
                port:
                  number: 80
